### ISSUE TITLE
UX EPIC: Roll-Out Login to Users

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1145]
**Issues**
- [x] #1217 
- [x] #1216  
   - [x] #1262 

- [x] #1250 
   - [ ] #1270 

- [x] #1304 

- [x] #1269
 
- [x] #1308 

Deprioritized
- [ ] #1218 

**Release Plan/ Timelines**
- [x] Have Cathy and Phoebe QA comms on Feb 29
- [x] Send first email comms on Mar 11
- [x] Send release email march 19
- [x] Release UI on March 19
- [ ] Hard cut over date - April 16 - send email follow-up

**Decisions**
- [x] What is our target date for transition? When will this come into effect for users?
- [x] How long will users have to do this? Will we still allow our old option? What happens if a user doesn't complete this?
- [x] What does "roll-out" look like for users?
- [ ] Is there a way to check-in/track which users partners that all have done this? Will we need one?
- [x] Where will we announce this release? Will anything be documented on Notify.gov? (see login.gov email templates)

**Comment by stvnrlly** [comment]
To be followed by #1476
