### ISSUE TITLE
Dashboard Data Viz: Improve how we display data

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1302]
### Description

**Current goal: synthesizing user feedback and developing implementation plan**

Message information is hard to find, displayed on a few different pages in different formats, and are questionably accurate (e.g. delayed). **How can we better organize schedule and sent message information to be more useful to different users?**

Hypothesis is that users need message information organized by:
- Individual jobs
- Individual Users
- Templates or folders - across relevant jobs and senders
- Service(s)

We will display scheduled and sent information on the following pages:

- Dashboard
- Activity/Jobs
- Templates (emerging)

### Delivery Outcomes
Decrease confusion of where to find sent and scheduled messages, their delivery status, and what these statuses mean, measured by more partner agencies using this status information in their outreach and outcome tracking activities. 

### Features (in order of priority/focus)
**NOW:**
**Improve API Endpoints for front-end usage**
- [x] #1529 
- [x] #1413 
- [x] https://github.com/GSA/notifications-api/issues/1006#issue-2303548715
   

**Ship: Allowance Countdown** 
- [ ]  #1484

**Ship: 7-day service-level dashboard data viz**
- [x] https://github.com/GSA/notifications-api/issues/1006

**Ship: 7-day indvidual-level dashboard data viz**
- [x] https://github.com/GSA/notifications-api/issues/1008

------
**NEXT:**
**Ship: Yearly (month-by-month) service-level dashboard data viz**
- [x] https://github.com/GSA/notifications-api/issues/1007

------

**DONE:**
**Feature: Research and Testing** 
- [x] #1288 
- [x] #1297 
- [x] #1482

**Comment by maomeara63** [comment]
- [ ] Review statuses returned by AWS and how they are used in Notify (in app and in reports)
- [ ] Map returned statuses to desired state to be presented to partners
- [ ] Provide description of what is in each state
- [ ] Review documentation
- [ ] Implement

**Comment by em-herrick** [comment]
Clickable prototype here: https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-4580&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580

**Comment by em-herrick** [comment]
Remove https://github.com/GSA/notifications-admin/issues/1492 from this Epic and add to next epic in backlog. We can close once we ship #1484
