### ISSUE TITLE
Prepare content/processes to support partners onboarding self-service

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1475]
**Acceptance Criteria**

- System Admin knows how to get started setting up Notify.gov for their team
- System Admin can accept a service invite and add additional users, understanding different permission options
- Users can learn how to get started and personalize content without our coaching
- Users know where to go if they have issues or bugs
- We have gotten feedback on our this experience directly from a self-service partner

### **Features**

**Feature: Review and Improve existing content**
- [x] #1287 
- [ ] #1510 
- [ ] #1290 
- [ ] Write new content
- [ ] Update Pricing page as new MOU is finalized (e.g. 500,000 messages)
- [ ] Update Usage numbers to reflect new MOUs
- [ ] Decide: Where new drafted content goes and if we need another behind-the-login page(s) for anything

**Feature: Finalize Onboarding processes and content for service set-up**

- [ ] #1527 
- [ ] Document the internal steps needed to create organization/phone number/service for new partners

**Feature: Operational customer support processes for bugs**
- [ ] Finalize written SLA
- [ ] Implement process/get product team aligned with approach
- [ ] Make sure support email is on comms and we have plan for managing it.

**Feature: Test Self-Service Experience**
- [ ] Get feedback on guidance page from a self-service partner after they have been onboarded/sent messages (AZ or not yet signed partner)

///

backlog (keeping handy for future epics)
- [ ] #1359 
- [ ] #689

**Comment by stvnrlly** [comment]
@ecayer will figure out which of these can be spun off into individual epics, as they seem large to us as-is

**Comment by em-herrick** [comment]
Closing because we've made smaller epics for this.
