### ISSUE TITLE
Improve and expand end-to-end (E2E) tests

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1540]
We have the foundations of end-to-end (E2E) tests in place now, but there are several things that still need some work.  We'd also like to add more E2E tests to improve our coverage and automate more of our QA process where it makes sense.

## Improve E2E tests and/or fix issues

- https://github.com/GSA/notifications-admin/issues/1267
- https://github.com/GSA/notifications-admin/issues/1157
- https://github.com/GSA/notifications-admin/issues/1520

Check QA Checklist and add to list of E2E tests.
## Add new E2E tests

- https://github.com/GSA/notifications-admin/issues/1338

- [ ] #1969
- [ ] - Creating a template
- [ ] - Download the csv delivery report
- [ ] - Invite a team member
- [ ] - Revalidate email address
- [x] #2073

**Comment by sheevdave** [comment]
Core Users
- Notify Champion
- Notify Administrator
- Campaign Manager
- Message Sender
- Data Wrangler
Source: [Notify Core Users](https://docs.google.com/presentation/d/1vq24dIDbYb0sB1Zi8T3rydV6iU4NClwkdnLfBfwpl9E/edit?usp=sharing)

**Comment by sheevdave** [comment]
[Created preliminary matrix to match current E2E tests with identified Notify Core Users](https://docs.google.com/spreadsheets/d/1gyzqq-M7kegQHbVLG2Z-R9CMUmmezllmoEHCoUSmuSc/edit?usp=sharing)

Meeting with @A-Shumway42 on 09/24 to see live demo of E2E tests

**Comment by ecayer** [comment]
I'll be especially interested in how the E2E tests match the core stories, rather than users. Which ones are covered in which tests? How many do we still have not-covered? 🍿

**Comment by em-herrick** [comment]
Identifying current coverage vs. ideal coverage and comparing them against core user stories

**Comment by sheevdave** [comment]
[Here's the breakdown of which tests fulfills which core-user function](https://docs.google.com/spreadsheets/d/1gyzqq-M7kegQHbVLG2Z-R9CMUmmezllmoEHCoUSmuSc/edit?usp=sharing). @terrazoon any thoughts on this and which ones we should create next?

**Comment by sheevdave** [comment]
@xlorepdarkhelm @A-Shumway42 will take a shot writing and pick 1 core-user story [in this spreadsheet](https://docs.google.com/spreadsheets/d/1gyzqq-M7kegQHbVLG2Z-R9CMUmmezllmoEHCoUSmuSc/edit?gid=0#gid=0) to write an E2E test for by the end of the sprint

**Comment by sheevdave** [comment]
this work is also tied the following tickets:

https://github.com/GSA/notifications-admin/issues/1934
https://github.com/GSA/notifications-admin/issues/1933

**Comment by ccostino** [comment]
This is being deprioritized.
