### ISSUE TITLE
Self-guided: Update partner support process

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1602]
Minimum viable process sketched out here: 

https://docs.google.com/document/d/19UY_wSok_xGL6M_1y6StTh9T7psp_yVclx_uhhopzgA/edit

Some to-dos:

- [x] Agree process - close down open questions in the doc
- [x] Update the notify e-mail address in partner-facing materials (where?)
- [x] Send out a request to partners to use the address in the future 
- [x] Agree when we'll revisit this process - done, 3 months & and in the calendar

**Comment by ecayer** [comment]
Agreed with @em-herrick and Cathy that we will not research with partners up-front. We think we know enough about how they are feeling, we are at risk of over-researching them, and some of the most interesting partners are still in the middle of support cases.
