### ISSUE TITLE
Write best practice content for behind login

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1793]
### Epic Goal
When we implement this Epic, texting practitioners will be able to access a new section on Notify.gov (top-level navigation) that outlines best practices gathered from other government texting programs on how to launch a successful texting campaign.

### To complete:

**Consolidate existing best-practices content**
- [x] Review [proposed Guidance Section](https://docs.google.com/document/d/10WVZMy8-fINZWiNQgNHsxruKtydMAEa17GKWb-H--5E/edit) in site outline
- [x] Review previously drafted materials (PDFs and presentations) on best practices
- [x] Consolidate existing content into Guidance Section outline

**Draft new Guidance Section**
- [x] Draft
- [x] Review / Edit
- [x] Approve

**Slim down `Using Notify` static content**
- [x] Review/edit existing Using Notify static page
   - [x] Remove any duplicative content that is duplicative of the new Guidance page (within a Google Doc)
   - [x] Rearrange/rewrite this page as needed
   - [ ] Approve new, slimmed down Using Notify page

**Comment by dmvancura** [comment]
referencing this [best practice spreadsheet](https://docs.google.com/spreadsheets/d/1W4FwGGHCcrZVxR8LdeohQs32hbVQRfKkcMqp8Jnzb90/edit?gid=0#gid=0) as well plus the additional resources listed in the best practice guide presentation

**Comment by em-herrick** [comment]
Considerations as we get content moving:

- Design changes / visuals
- Video options (production, accessibility/transcript, hosting)
- integration with other user flows

What do we do with partner "tools"
- [ ] Check-lists
- [ ] Worksheets
- [ ] Linked examples
