### ISSUE TITLE
Get pricing approach defined and approved.

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1820]
Updated after LBS conversation:

- [x] Summarize LBS conversation
- [x] Meeting Jackie's consultant about modelling.
- [ ] Get information from Jackie on calculating Notify's portion of Accelerators fix overhead costs
- [x] Finalize pricing [One-pager](https://docs.google.com/document/d/1vogN1YYluPDdiUS3uwBKjvvk6KB5qxr4cvvaL2Eoz0M/edit) & get approved 
- [ ] Define pricing approach that matches requirements of memo (+ Jen from BizOps)
- [x] #1979
- [ ] Iterate on those according to the RACI
- [ ] Draft a formal pricing memo

Aiming to get as much of this as possible done before the Sep 9 meeting with LBS (ideally by Sep 5 for pre-reading)

**Comment by ecayer** [comment]
Brought in support from Matt (TC) for modeling the potential pricing approaches

**Comment by ccostino** [comment]
We're in a different phase now; closing this issue.
