### ISSUE TITLE
Prep for next deploy & roll out new UI changes to users

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1835]
### Epic Goal
When we implement this Epic, users will be able to view new dashboard updates (allowance bar, 7-day message count data viz, and new table layouts) and a new activity page. 

They will have a clear sense of what changes to expect and are able to complete all normal/existing user stories.

### Finish deploying to staging
- [x] Review & push PR #1817 
- [x] Review & push PR  #1674 
- [x] Fix image issue on landing page
  

### QA
TEAM: @dmvancura @sheevdave  @ecayer @em-herrick 
- [x] Go through normal QA checklist (in an issue template) 

- [ ] **Data Viz** 
     - [ ] Send a batch of messages (more than one-offs), force some fails 
     - [ ] Check tables against messages that were sent
 - [x] **New Activity Page**
      - [ ] make sure pagination works
      - [ ] Download CSV file
      - [ ] New jobs should list at the top of table
      - [ ] Date and time should be accurate

### Release 
- [ ] #1826

**Comment by em-herrick** [comment]
@ccostino can you share the AWS number you mentioned we could use to push some messages to "failed"?

**Comment by ccostino** [comment]
Yes, those are all found here in AWS' docs! https://docs.aws.amazon.com/sms-voice/latest/userguide/test-phone-numbers.html#test-phone-numbers-destination

Specifically for the US:

Country | Status | Number
-- | -- | --
United States | Success | +14254147755
United States | Failure | +14254147167
