### ISSUE TITLE
Design, implement, and approve public partnership/sales pages (Home page phase 1)

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1867]
### Epic Goal
When we implement this epic, interested Notify.gov users will be able to view partnerships process content and better understand available features of Notify.gov via public content pages.

### Epic Why
As Notify.gov gets approval from TTS leadership to move out of pilot and into beta, there is opportunity to increase our publicly available content, focused on continuing to build our partnerships pipeline. 

### To Complete

This content will need to be designed and implemented before going through the TTS/GSA approval process.

- [x] #1985
- [x] #2047
- [x] #2090
- [x] Match USDS components, build new ones
- [x] Get content approved by GSA/TTS
- [x] Import locked content into page templates
- [x] Ship to sandbox for testing and feedback
- [x] #2109

**Comment by em-herrick** [comment]
Wireframe of Notify.gov
Wireframe of landing page
content in a google doc

**Comment by dmvancura** [comment]
to complete

- [ ] [fix links in about us & join notify pages](https://github.com/orgs/GSA/projects/20/views/1?filterQuery=about&pane=issue&itemId=91674256&issue=GSA%7Cnotifications-admin%7C2224)
- [ ] [add Join Notify to main nav](https://github.com/GSA/notifications-admin/issues/2240)
- [ ] [contact](https://github.com/orgs/GSA/projects/20/views/1?filterQuery=contact&pane=issue&itemId=86968026&issue=GSA%7Cnotifications-admin%7C2105)
- [ ] [move 'Contact' up into the public main navigation](https://github.com/orgs/GSA/projects/20/views/1?pane=issue&itemId=92481713&issue=GSA%7Cnotifications-admin%7C2241)

@VRagulina depending on my github permissions i made need help moving this into the main task

**Comment by jonathanbobel** [comment]
- [ ] #2282

**Comment by ecayer** [comment]
Agree, @heyitsmebev ! Corrected the title, changed checklist, and closing.
