### ISSUE TITLE
Prepare for Census 100,000 message send

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#2142]
The team is preparing for a first “large” send of (100,000) messages. Accepting this partner is in line with the product strategy of supporting high-volume partners in order to ultimately secure paid partnerships.

The team expressed a high level of confidence that with thoughtful batching, the new partner would be successful.

## High level tasks 

- [x] (Cathy & Stvn) talk to Census about batching. Find out what impact of carrier throttling would be. Also potentially review the actual message to ensure it’s one message part
- [x] (Carlo?) Watch for what memory does during this week (possibly look for prior spikes and see how high they went / how many messages were going out) 
   - Update 11/25/24 - Carlo sent out a cloud.gov support request asking for metrics of our database the application
- [x] (Ken) Load testing on prod - working through details on Slack
   - This was conducted on 11/22/24
- (?) The day before send-day, make final deployments and up the memory on prod. 
- (?) Clarify any extraordinary “on-call” expectations (which I think are “none” :-) ) 
- (?) Think through the possibilities for avoiding/detecting/mitigating carrier throttling (did not get to it in the session, but clearly high on people’s minds!)
- (?) Give AWS and cloud.gov a heads-up

## Specific engineering tasks

- [ ] https://github.com/GSA/notifications-api/issues/1391
- [x] https://github.com/GSA/notifications-api/issues/1430
- [ ] https://github.com/GSA/notifications-api/issues/1432
- [x] https://github.com/GSA/notifications-api/issues/1426
- [x] https://github.com/GSA/notifications-api/issues/1431
- [x] https://github.com/GSA/notifications-api/issues/1390
- [x] https://github.com/GSA/notifications-api/issues/1436

## Addressing errors/false positives in New Relic

- [ ] https://github.com/GSA/notifications-api/issues/1396
- [ ] https://github.com/GSA/notifications-api/issues/1392

**Comment by ecayer** [comment]
We prepared. Now we are cleaning up! Remaining issues carried over to https://github.com/GSA/notifications-admin/issues/2181
