### ISSUE TITLE
Implementing first-round of a11y fixes

### ISSUE THREAD

**Issue by sheevdave** [GSA/notifications-admin#2172]
### Epic Goal
When we implement this epic, new users will:
-see some improvements in the dashboard and send-message flow cadence
-integrate a11y in CI/CD 

### Epic Why
Continuing our effort to continuously integrating accessibility standards into our product. 

### To Complete

- [ ] https://github.com/GSA/notifications-admin/issues/2081
- [ ] https://github.com/GSA/notifications-admin/issues/2080
- [ ] https://github.com/GSA/notifications-admin/issues/2079
- [ ] https://github.com/GSA/notifications-admin/issues/2095

- [ ] https://github.com/GSA/notifications-admin/issues/1932#issue-2520451218
- [ ] [Add a11y test automation in the local test suite](https://github.com/GSA/notifications-admin/issues/1933)
- [ ] [Add a11y test automation in CI](https://github.com/GSA/notifications-admin/issues/1934)
- [ ] [Configure cadence for manual testing](https://github.com/GSA/notifications-admin/issues/1935)
- [ ] Incorporate accessibility testing and considerations into Definition of Done in User Story issue template
