### ISSUE TITLE
Platform Admin enhancements

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#2237]
As we've begun processing more information/data through the system and supporting more partners, it's becoming clear that we need some additional functionality in our platform admin interface and/or our team members with platform admin access.  These improvements will enable us to provide our partners with better support as well as take care of system issues more easily.

- [ ] Add monitoring for Redis in the platform admin (what it's current overall memory usage is; size of Celery-related keys)
- [ ] Add the ability for a platform admin to retrieve user-uploaded CSVs and/or the job CSVs
- [ ] Add ability to see overall message send statistics for all partners
- [ ] Improve the way we're able to see and access partner services
