### ISSUE TITLE
Grow Notify team to ~7 full-time staff

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#241]
- [x] https://github.com/GSA/public-benefits-studio/issues/183
- [x] https://github.com/GSA/notifications-admin/issues/214
- [x] Outline reassignment process
- [x] #266 
- [x] #339 
- [x] #310 
- [x] #311

**Comment by ccostino** [comment]
We did accomplish this! 🎉 

🫗 for the team as it was at that point; we're in a different phase now!
