### ISSUE TITLE
Build out partnerships tracker in airtable

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#268]
...so that it's easier to have a high level view of where we're at with all potential partners, and drill down to details/next actions for each opportunity/relationship.

To do:

- [x] @tdlowden & @alexpandel take 1st pass at mapping out the actual steps/funnel path [here](https://app.mural.co/t/gsa6/m/gsa6/1671653725218/73684e9bac662d4dd733941c819f887bb623d0f5?sender=alexandrapandel)
- [x] take 2nd pass at mapping out path for each engagement type, looping in @em-herrick 
- [x] @alexpandel take pass through structuring the kanban/template card setup in [airtable tracker](https://airtable.com/appEdCi7qdLaYUBhb/tblhkLXizp682JLGD/viw0KDvQvvkvsJZs9?blocks=hide)
- [ ] @amyashida change permissions to allow access for @tdlowden 
- [ ] outreach crew meet to talk through all current leads and get them entered into the tracker

**Comment by amyashida** [comment]
Mural where this is being mapped out [here](https://app.mural.co/t/gsa6/m/gsa6/1671653725218/73684e9bac662d4dd733941c819f887bb623d0f5?sender=amyashida5338)

**Comment by alexpandel** [comment]
assigning the next steps to me and Amy, but will tag @em-herrick & @tdlowden back in once I have a pass at the base ready for review!

**Comment by alexpandel** [comment]
ok @tdlowden & @em-herrick, I took a 1st pass at a framework for [the tracker here](https://airtable.com/appEdCi7qdLaYUBhb/tblhkLXizp682JLGD/viw581bY8GuuGicyd?blocks=hide); we can talk thru it during outreach sync on Monday!
