### ISSUE TITLE
Complete + execute agreements to allow us to work with SLTTs

### ISSUE THREAD

**Issue by amyashida** [GSA/notifications-admin#303]
If our partner is not a federal agency, we need to have authority to work with them either through an IGCA or through an agreement with a federal agency that provides services to SLTTs. 

For a "pass-through" agreement: 

- [x] #252
- [x] #304 
- [x] Identify post-signature recruitment SLTT strategy with partner
- [x] Get partner signatures
- [x] Get TTS/OGC signatures 

For the IGCA: 
- [x] #263

**Comment by ccostino** [comment]
This work had been completed previously and we have details and lessons learned documented; closing this issue!
