### ISSUE TITLE
Intergrate one-pager content into static content on Notify.gov

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#449]
- [x] Pull down / audit existing content: Using Notify & Features
- [x] Prioritize which [one-pagers / content](https://docs.google.com/spreadsheets/d/1dOCeu1yIa7yJboyxeIQNH6HnV9RO4KG_gZMEk99dOfo/edit#gid=0) should be included in this iteration

- [x] Prioritize and discuss additional Notify.gov key open questions from these docs
- [Notify Feedback--General Questions](https://docs.google.com/spreadsheets/d/1Nq3LIpKB_rOGA4UbsTHZ2EPkQTnZxuWHtx7ZVNs-D_Y/edit#gid=0)
- [Notify Tough Questions FAQ](https://docs.google.com/document/d/1RI62u4hNQT8iOn1uUo6r9t3KoP9MYArHCnVBaoB1Yac/edit#heading=h.cb2kqlh0ij7z)

- [x] Outline/first draft of new content 
- [x] Team review, feedback
- [ ] Feedback from partners
- [x] Sign-off (from studio team)
- [x] Deploy! (Early feb?)

**Comment by maomeara63** [comment]
[Draft Messaging Strategy](https://docs.google.com/presentation/d/1Tq4jcP8iwvvjfkUizHAGfrsbrqFODw9fO0lnrxDpRjw/edit?usp=sharing)

**Comment by tdlowden** [comment]
Messaging strategy review before closing (style guide is covered in #481 :

- [ ] @em-herrick 
- [ ] @tdlowden

**Comment by em-herrick** [comment]
I have done a review and I am loving where the Content strategy deck is going, but I think it needs a bit more collaborative thought and review of existing research notes. I have added a bunch of (admittedly rambly) comments. 

Now that I am back from leave and conferencing, I am hoping to jump back into partner convo synthesis and come back to this with a more ground direction. 

While what we have is great for Notify, I'd also like to expand this deck to Notifications content. So would like to add a few more personas in and maybe another slide to delineate.

Happy to have this reassigned to me (or close the issue and I can move it forward outside of Github).

**Comment by tdlowden** [comment]
Ok, thanks @em-herrick. I am re-assigning to you and moving into `Up Next` for you to grab when you take up the work

**Comment by tdlowden** [comment]
I think it's time to pick this back up and start meeting to scope what we want things to look like @em-herrick @maomeara63. Going to move this into `up next`

**Comment by em-herrick** [comment]
@tdlowden -- Meghan and i have time to checkin about this tomorrow 12/20. We can devise a plan and report out, or you're welcome to join (at 10am)

**Comment by maomeara63** [comment]
@tdlowden @em-herrick 

Some of the static page content is ready for review:

**Ready for review**
[Get started ](https://docs.google.com/document/d/1C-a32U2dbrIHo40BWwgcqJvRi41Afsiq_3T30FlpVAA/edit?usp=drive_link)(revised following Tim/Em comments)
[Trial Mode](https://docs.google.com/document/d/1BHeLKMbM7oboWq2lxHiaFuLjJlO5qcuZdA9l3GD9muU/edit?usp=drive_link)
[Guidance](https://docs.google.com/document/d/1v03v8VLxH9fkGYtFFI3HfgEtp4mqyimw5oY67IbPY6A/edit?usp=drive_link)
[Contact us
](https://docs.google.com/document/d/1XNj44Dh3Vb9t0gFzeHSfy5zp2ZrmAOm862tanjMxhxA/edit?usp=sharing)

**Prepped for Tim's review**
[Roadmap](https://docs.google.com/document/d/1HLtoqev_zVgJd6DjKKsq5aC7FaPXpyIdEpkvHQrHXHk/edit?usp=drive_link)
[Security](https://docs.google.com/document/d/1ZxaGfMifIqE5LwyWGwG1C9GRsj1Bi6VK2NJYbeEICzg/edit?usp=drive_link)
[Terms of use](https://docs.google.com/document/d/1W_SgnzwRPYWWWBtJ83RmXhY-Ya28Z93O_63NHl7vYnk/edit?usp=drive_link)

**Waiting**
Pricing (waiting for "parts" changes to be pushed to Prod)
Delivery status (waiting for UTC changes to be pushed to Prod)
Features (waiting for us to figure out how to use this space)

**Comment by em-herrick** [comment]
@maomeara63 I have reviewed!

**Comment by tdlowden** [comment]
I think all the above content is now ready for implementation. Seems like the best way to do it would be to scrap what's in there, lay all the new content, and format it.

**Comment by em-herrick** [comment]
@em-herrick and @tdlowden to discuss terms of use and decide what we want to do with this

**Comment by maomeara63** [comment]
@jonathanbobel These are ready to be loaded:


- [Get started ](https://docs.google.com/document/d/1C-a32U2dbrIHo40BWwgcqJvRi41Afsiq_3T30FlpVAA/edit?usp=drive_link)(revised following Tim/Em comments)
- [Trial Mode](https://docs.google.com/document/d/1BHeLKMbM7oboWq2lxHiaFuLjJlO5qcuZdA9l3GD9muU/edit?usp=drive_link)
- [Guidance](https://docs.google.com/document/d/1v03v8VLxH9fkGYtFFI3HfgEtp4mqyimw5oY67IbPY6A/edit?usp=drive_link)
- [Contact us](https://docs.google.com/document/d/1XNj44Dh3Vb9t0gFzeHSfy5zp2ZrmAOm862tanjMxhxA/edit?usp=sharing)
- [Roadmap](https://docs.google.com/document/d/1HLtoqev_zVgJd6DjKKsq5aC7FaPXpyIdEpkvHQrHXHk/edit?usp=drive_link)
- [Security](https://docs.google.com/document/d/1ZxaGfMifIqE5LwyWGwG1C9GRsj1Bi6VK2NJYbeEICzg/edit?usp=drive_link)

**Comment by maomeara63** [comment]
@jonathanbobel, please fix:

- Link to pricing page on [Contact Us](https://docs.google.com/document/d/1XNj44Dh3Vb9t0gFzeHSfy5zp2ZrmAOm862tanjMxhxA/edit?usp=sharing)
- The in-page link to Identify your program on [Guidance ](https://docs.google.com/document/d/1v03v8VLxH9fkGYtFFI3HfgEtp4mqyimw5oY67IbPY6A/edit?usp=sharing)
- The link to Send messages in [Guidance](https://docs.google.com/document/d/1v03v8VLxH9fkGYtFFI3HfgEtp4mqyimw5oY67IbPY6A/edit?usp=sharing)
- Is it possible to add a checkmark after the Achieve compliance to begin piloting line in [Roadmap?](https://docs.google.com/document/d/1HLtoqev_zVgJd6DjKKsq5aC7FaPXpyIdEpkvHQrHXHk/edit?usp=sharing)
- Can you make **Next** an H3 on [Roadmap?](https://docs.google.com/document/d/1HLtoqev_zVgJd6DjKKsq5aC7FaPXpyIdEpkvHQrHXHk/edit?usp=sharing)
- Please delete "high impact" from the first sentence under "Next" on [Roadmap](https://docs.google.com/document/d/1HLtoqev_zVgJd6DjKKsq5aC7FaPXpyIdEpkvHQrHXHk/edit?usp=sharing)
- On [Security](https://docs.google.com/document/d/1ZxaGfMifIqE5LwyWGwG1C9GRsj1Bi6VK2NJYbeEICzg/edit?usp=sharing), the graphic is in the wrong place. Can you move it up under "hide personalization"?
- On [Security,](https://docs.google.com/document/d/1ZxaGfMifIqE5LwyWGwG1C9GRsj1Bi6VK2NJYbeEICzg/edit?usp=sharing) please delete the H4 How to hide PII after sending a message. My error.
- On Security, User permissions and signing in is on the page twice. Please remove one of them. 
- On Security, I'm waiting for @tdlowden to provide a link to ATO.
