### ISSUE TITLE
1-year LATO

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#63]
Leading: @rahearn 
Supporting: @stvnrlly 

Process:

- [x] https://github.com/GSA/public-benefits-studio/issues/163
- [x] #91
- [x] #262
- [x] #220 
- [x] https://github.com/GSA/public-benefits-studio/issues/162
- [x] #62 
- [x] #295
- [x] #296
- [x] #294
- [x] #307
- [x] #308
- [x] #359
- [x] #360
- [x] #297

Dev work:
- [x] https://github.com/GSA/notifications-api/issues/70
- [x] https://github.com/GSA/notifications-api/issues/38
- [x] https://github.com/GSA/notifications-api/issues/137
- [x] https://github.com/GSA/notifications-admin/issues/55
- [x] #255 
- [x] https://github.com/GSA/notifications-api/issues/167
- [x] #344
- [x] #429 
- [x] #346 
- [x] #461
- [x] https://github.com/GSA/notifications-api/issues/234

---
Possible stories, need further scoping:
- [ ] Better define reporting needs and data guardrails we can put in place for pilot

**Comment by tdlowden** [comment]
Obviously, the ATO process is a billion smaller parts than this. @rahearn, do you think we should make this an EPIC card and list steps in the process, or would you prefer just to label individual tasks with ATO label as you work through? Open to either. If the latter, feel free to close this card.

**Comment by rahearn** [comment]
I'll fill in the tasks after the meeting with Ryan Palmer on 9/16

**Comment by rahearn** [comment]
Scheduled system name email to be sent 9/26 when Ryan P. is back

**Comment by rahearn** [comment]
Email requesting an ISSO sent on 9/26

**Comment by rahearn** [comment]
Keep https://docs.google.com/document/d/1Zn0CTZe9SzmTABw5iKHZXgH9tFiIGlRwqz6jdW0ai2A/edit#heading=h.7a05tu0aa3f up-to-date throughout process
