### ISSUE TITLE
create epics and potentially milestones?

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#72]
- [x] synthesize data from sprint plan meeting
- [x] create epics that relate to the priorities
- [x] if needed, create larger, overarching milestones
