### ISSUE TITLE
Notify research, round 1

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#77]
- [x] Complete pilot scoping
- [x] Identify the product hypotheses we can try to answer pre-pilot
- [x] Create a user interview template
- [ ] Engage with a diverse group of testers to interview
- [x] Synthesize learnings
- [ ] Incorporate learnings into tool/strategy or adjust approach as necessary
- [x] https://github.com/GSA/notifications-admin/issues/199

**Comment by amyashida** [comment]
Did this already happen? What is left here?

**Comment by tdlowden** [comment]
Tagging @em-herrick here to get her thoughts on where we stand.
