### ISSUE TITLE
Sign agreement with first pilot partner

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#78]
Leading: @tdlowden 
Supporting: @amyashida 

- [x] #232 
- [x] #199
- [x] Determine if/what data sharing agreements are necessary
- [x] Get OGC/TTS signatures
- [x] Get partner signatures

Dependencies: 

- [x] #251 @tdlowden leading (needed for any partner) 
- [x] #252 @amyashida leading (only needed for SLTT partners w/out IGCA)
- [x] #305 @amyashida leading
